### ISSUE TITLE
shape.txt has lat/lon reversed!

### ISSUE THREAD

**Issue by elf-pavlik** [UlmApi/livemap#10]
https://developers.google.com/transit/gtfs/reference#shapes_fields
gives order: shape_id,shape_pt_lat,  shape_pt_lon, shape_pt_sequence, shape_dist_traveled
your file has: shape_id,shape_pt_lon,shape_pt_lat,shape_pt_sequence

**Comment by fnogatz** [comment]
Solved by 650474e.
